copy C:\PassPKit\Bin\TestDrvx86.pdb D:\VMwareMachine\Windows7X86-LocalSym\TestDrvx86.pdb /y
copy C:\PassPKit\Bin\TestDrvx64.pdb D:\VMwareMachine\Windows7X64-LocalSym\TestDrvx64.pdb /y
copy C:\PassPKit\Bin\TestDrvx86.pdb D:\VMwareMachine\Windows8X86-LocalSym\TestDrvx86.pdb /y
copy C:\PassPKit\Bin\TestDrvx64.pdb D:\VMwareMachine\Windows8X64-LocalSym\TestDrvx64.pdb /y
copy C:\PassPKit\Bin\TestDrvx86.pdb D:\VMwareMachine\Windows8.1X86-LocalSym\TestDrvx86.pdb /y
copy C:\PassPKit\Bin\TestDrvx64.pdb D:\VMwareMachine\Windows8.1X64-LocalSym\TestDrvx64.pdb /y
copy C:\PassPKit\Bin\TestDrvx86.pdb D:\VMwareMachine\Windows10X86-LocalSym\TestDrvx86.pdb /y
copy C:\PassPKit\Bin\TestDrvx64.pdb D:\VMwareMachine\Windows10X64-LocalSym\TestDrvx64.pdb /y
copy C:\PassPKit\Bin\TestDrvx86.pdb D:\VMwareMachine\WindowsXp-LocalSym\TestDrvx86.pdb /y